#!/usr/bin/env python
import os
import sys

env = SConscript("godot-cpp/SConstruct")


## MY EXTRAS
## adding muparser, expression parsing can be used for waves
muparser_dir = 'external/muparser/'
env.Append(CPPPATH=[muparser_dir])  # Include path for headers
env.Append(SOURCES=[
    muparser_dir + '/src/muParser.cpp',
    muparser_dir + '/src/muParserBase.cpp',
    muparser_dir + '/src/muParserBytecode.cpp',
    muparser_dir + '/src/muParserCallback.cpp',
    muparser_dir + '/src/muParserError.cpp',
    muparser_dir + '/src/muParserTokenReader.cpp',
])
## endregion


# For reference:
# - CCFLAGS are compilation flags shared between C and C++
# - CFLAGS are for C-specific compilation flags
# - CXXFLAGS are for C++-specific compilation flags
# - CPPFLAGS are for pre-processor flags
# - CPPDEFINES are for pre-processor defines
# - LINKFLAGS are for linking flags

# tweak this if you want to use different folders, or more folders, to store your source code in.
env.Append(CPPPATH=["src/"])
sources = Glob("src/*.cpp")

if env["platform"] == "macos":
    library = env.SharedLibrary(
        "demo/bin/libgdexample.{}.{}.framework/libgdexample.{}.{}".format(
            env["platform"], env["target"], env["platform"], env["target"]
        ),
        source=sources,
    )
elif env["platform"] == "ios":
    if env["ios_simulator"]:
        library = env.StaticLibrary(
            "demo/bin/libgdexample.{}.{}.simulator.a".format(env["platform"], env["target"]),
            source=sources,
        )
    else:
        library = env.StaticLibrary(
            "demo/bin/libgdexample.{}.{}.a".format(env["platform"], env["target"]),
            source=sources,
        )
else:
    library = env.SharedLibrary(
        "demo/bin/libgdexample{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
        source=sources,
    )

Default(library)
